/**
 * @author      : Karthik	
 * @date        : 08-06-2023
 * @Description : Calculator program using class
 * 
 **/

public class Day6Diy1 {
    Integer num1=1;
    Integer num2=2;
    
    public void sum() {
		Integer sum = num1 + num2;
        system.debug(sum);
    }
        public void sub() {
		Integer subraction = num1 - num2;
        system.debug(subraction);
    }

        public void mul() {
		Integer multiply = num1 * num2;
        system.debug(multiply);
    }

        public void div() {
		Integer division = num1 / num2;
        system.debug(division);
    }

}